### ISSUE TITLE
Custom bot commands

### ISSUE THREAD

**Issue by rahul-instinct** [azamaulanaaa/botkaca#11]
Please add support of custom commands for bot

**Comment by azamaulanaaa** [comment]
can you explain more? what its? and how it works?

**Comment by rahul-instinct** [comment]
> 
> 
> can you explain more? what its? and how it works?

we can use our commands for leech or thumbnail set and remove 
for example instead of leech command I want to use dl or any other command

**Comment by azamaulanaaa** [comment]
you can modified command at `/bot/__init__.py` for default one or you can modified it using environment variable. `COMMAND_` + command key, check on `/bot/__init__.py`. Ex. for leech set env var `COMMAND_LEECH`.

btw I miss something, let me fix a moment

**Comment by azamaulanaaa** [comment]
sorry wrong issue reference for https://github.com/azamaulanaaa/botkaca/commit/b9da7eb2c7c7a24413e5f7f14064d5128d2c0748 it should be for #13
