### ISSUE TITLE
#Req Features

### ISSUE THREAD

**Issue by MaxxRider** [azamaulanaaa/botkaca#18]
👲If possible add These Feature 👇

1= Custome File Name support
2= Thumbnail save via Command instead of Caption
3= Unzip ,unrar ,zip, untar
4=Fix thumbnail issue in upload as Doc

**Comment by azamaulanaaa** [comment]
Duplicate of #8 #14 #15  #12

**Comment by azamaulanaaa** [comment]
oh sorry, I missed no 2. Thumbnail save via caption I think the best way to do it because it has less complexity and change thumbnail in one action.

**Comment by MaxxRider** [comment]
ok atleast Add  Custome File Name support 🙈
custome File Name is important thing I think
