### ISSUE TITLE
HEROKU APP BUILD CRASH

### ISSUE THREAD

**Issue by talkaal** [azamaulanaaa/botkaca#7]
**HEROKU has updated terms of service.
Based on that there's a issue .**

Bulid log from step 7.

Step 7/7 : CMD ["python3", "-m", "bot"]
 ---> Running in 99f029eaf2d0
Removing intermediate container 99f029eaf2d0
 ---> fcb039d993b0
Successfully built fcb039d993b0
Successfully tagged 12a2583fe9637aeeb08734c7eacd32c6e6b4c18c:latest
=== Pushing worker (Dockerfile)
Tagged image "12a2583fe9637aeeb08734c7eacd32c6e6b4c18c" as "registry.heroku.com/pure-earth-39958/worker"
The push refers to repository [registry.heroku.com/pure-earth-39958/worker]
Get https://registry.heroku.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
=!= Build failed due to an error:
=!= push step: exit status 1
If this persists, please contact us at https://help.heroku.com/.

![Screenshot_2020-10-01-14-16-17-608_com android chrome](https://user-images.githubusercontent.com/68809670/94788491-41bf7480-03f1-11eb-9884-78de4e430d23.jpg)

**Comment by talkaal** [comment]
> HEROKU has updated terms of service.
Based on that there's a issue .

https://devcenter.heroku.com/changelog-items/1923

**Comment by azamaulanaaa** [comment]
I have been tried a moment ago and it works just fine. Any idea to replicate the bug?
