### ISSUE TITLE
Download link support

### ISSUE THREAD

**Issue by rahul-instinct** [azamaulanaaa/botkaca#9]
Please add download support for other links too like anonfile zippyshare upcloud...
For example https://github.com/lzzy12/python-aria-mirror-bot/blob/master/bot/helper/mirror_utils/download_utils/direct_link_generator.py

**Comment by azamaulanaaa** [comment]
that feature never be release. this app only leech to telegram. thank you

**Comment by rahul-instinct** [comment]
> 
> 
> that feature never be release. this app only leech to telegram. thank you

i want to download files from those links and upload those to telegram
whenever i try to download any file from those url it only download inex,html

**Comment by azamaulanaaa** [comment]
sorry, but that too never be released. only direct link that supported.
